spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/contacts
    username: postgres
    password: testtest
    hikari:
      schema: contacts_schema
    driver-class-name: org.postgresql.Driver