spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6432/rest_db
    username: postgres
    password: postgres
    hikari:
      schema: rest_schema
      connection-ini-sql: CREATE schema  if not exists rest_schema
      connection-timeout: 10000
    driver-class-name: org.postgresql.Driver

app:
  check-client-api-header: false
  client-api-key: 12345
  security:
    type: db

permissions:
  advanced:
    - ROLE_ADMIN
    - ROLE_MODERATOR