spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:6432/hotel_booking
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
      connection-ini-sql: CREATE schema  if not exists booking_schema
      connection-timeout: 10000
    driver-class-name: org.postgresql.Driver