spring:
  main:
    allow-circular-references: true

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-ini-sql: CREATE schema  if not exists app_schema
      connection-timeout: 10000
    driver-class-name: org.postgresql.Driver


app:
  redis:
    enable: true
  integration:
    base-url: http://localhost:8082
  cache:
    cacheType: redis
    cache-names:
      - databaseEntities
      - databaseEntityByName
    caches:
      databaseEntities:
        expire: 10m
      databaseEntityByName:
        expire: 10m
      databaseEntitiesById:
        expire: 10m
