version: '3'
services:
  postgres:
    container_name: hotel_booking
    image: postgres:12.3
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_booking
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql